config-version = 1
fade-time = 0.24709302325581395
mod-enabled = true
animation-curve = 1
fade-type = 0
fade-enabled = true
animation-enabled = false
animation-offset = 64.0
show-mod-button-in-settings = false
animate-near-player = false
update-notifier-enabled = false
animation-time = 1.002906976744186
